[project]
name = "gtfs-ontology"
version = "0.2.0"
description = "Source code to produce an OWL ontology for the General Transit Feed Specification."
authors = [
    {name = "Joseph Preece", email = "joseph.preece@glasgow.ac.uk"}
]
dependencies = [
    "owlready2 == 0.50",
    "pyyaml == 6.0.3",
    "rdflib == 7.2.1",
    "morph-kgc == 2.10.0",
    "pytest == 9.1.1",
    "pyshacl == 0.31.0",
    "markdown == 3.10.3",
    "lxml == 6.1.3"
]