[DEFAULT]
main_dir = ..

[CONFIGURATION]
output_file = ../artefacts/graphs/west_midlands.nt
output_format = N-TRIPLES
;logging_level = DEBUG

[Agencies]
mappings = ${main_dir}/artefacts/mappings/agency.rml.ttl
file_path = ${main_dir}/data/agency.csv

[Stops]
mappings = ${main_dir}/artefacts/mappings/stops.rml.ttl
file_path = ${main_dir}/data/stops.csv

[Routes]
mappings = ${main_dir}/artefacts/mappings/routes.rml.ttl
file_path = ${main_dir}/data/routes.csv

[Trips]
mappings = ${main_dir}/artefacts/mappings/trips.rml.ttl
file_path = ${main_dir}/data/trips.csv

[StopTimes]
mappings = ${main_dir}/artefacts/mappings/stop_times.rml.ttl
file_path = ${main_dir}/data/stop_times.csv