# An AgencyFile is an AgencyFileWithMultipleAgencies if it has more than one Agency.
[?f, rdf:type, gtfs:AgencyFileWithMultipleAgencies] :-
    [?f, rdf:type, gtfs:AgencyFile] ,
    [?f, gtfs:hasAgency, ?a1],
    [?f, gtfs:hasAgency, ?a2],
    FILTER(?a1 != ?a2).

# Single‑agency if it has at least one agency AND it is not multi agency file.
[?f, rdf:type, gtfs:AgencyFileWithSingleAgency] :-
    [?f, rdf:type, gtfs:AgencyFile] ,
    [ ?f, gtfs:hasAgency, ?a ],
    NOT EXISTS ?x IN (
        [?f, rdf:type, gtfs:AgencyFileWithMultipleAgencies]
    ).

# Raise a violation if the file is neither a single or multiple agency file.
[?f, rdf:type, gtfs:Violation] :-
    [?f, rdf:type, gtfs:AgencyFile] ,
    NOT EXISTS ?x IN ([ ?f, rdf:type, gtfs:AgencyFileWithSingleAgency ]) ,
    NOT EXISTS ?y IN ([ ?f, rdf:type, gtfs:AgencyFileWithMultipleAgencies ]) .

# Raise a violation if two agencies have the same id.
[?a1, rdf:type, gtfs:Violation],
[?a2, rdf:type, gtfs:Violation] :-
    [?a1, gtfs:agency_id, ?i] ,
    [?a2, gtfs:agency_id, ?i] ,
    FILTER(?a1 != ?a2).

# Check for the required name field.
[?a, gtfs:violationDetail, "This `Agency` does not have an `agency_name`."] ,
[?a, rdf:type, gtfs:Violation] :-
    [?a, rdf:type, gtfs:Agency] ,
    NOT EXISTS ?n IN ([?a, gtfs:agency_name, ?n]) .

# Check for the required URL field.
[?a, gtfs:violationDetail, "This `Agency` does not have an `agency_url`."] ,
[?a, rdf:type, gtfs:Violation] :-
    [?a, rdf:type, gtfs:Agency] ,
    NOT EXISTS ?u IN ([?a, gtfs:agency_url, ?u]) .

# Check for the required timezone field.
[?a, gtfs:violationDetail, "This `Agency` does not have an `agency_timezone`."] ,
[?a, rdf:type, gtfs:Violation] :-
    [?a, rdf:type, gtfs:Agency] ,
    NOT EXISTS ?t IN ([?a, gtfs:agency_timezone, ?t]) .

# Check if agencies within a multiple agency file have unique ids.
[?d, gtfs:violationDetail, "This `Agency` does not have an `agency_name`."] ,
[?a, rdf:type, gtfs:Violation] :-
    [?f, rdf:type, gtfs:AgencyFileWithMultipleAgencies],
    [?f, gtfs:hasAgency, ?a],
    NOT EXISTS ?id IN ([?a, gtfs:agency_id, ?id]).

# Assign the appropriate description to the CEMV support fields.
[?a, gtfs:cemv_support_description, gtfs:CEMVSupportDatatypeDescriptionAgency0] :-
    [?a, rdf:type, gtfs:Agency],
    [?a, gtfs:cemv_support, 0].

[?a, gtfs:cemv_support_description, gtfs:CEMVSupportDatatypeDescriptionAgency1] :-
    [?a, rdf:type, gtfs:Agency],
    [?a, gtfs:cemv_support, 1].

[?a, gtfs:cemv_support_description, gtfs:CEMVSupportDatatypeDescriptionAgency2] :-
    [?a, rdf:type, gtfs:Agency],
    [?a, gtfs:cemv_support, 2].

# Raise a violation if the CEMV support field is not 0, 1, or 2.
[?a, rdf:type, gtfs:Violation] :-
    [?a, gtfs:cemv_support, ?v],
    FILTER(?v != 0 && ?v != 1 && ?v != 2).