[gtfs:Violation, rdf:type, owl:Class] .

# 1) STOP IDs
## a) A Stop must have a stop_id.
## b) All stop_ids must be unique.

## 1a
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Stop] ,
    NOT EXISTS ?i IN (
        [?s, gtfs:stop_id, ?i]
    ) .

## 1b
[?s1, rdf:type, gtfs:Violation],
[?s2, rdf:type, gtfs:Violation] :-
    [?s1, gtfs:stop_id, ?i] ,
    [?s2, gtfs:stop_id, ?i] ,
    FILTER(?s1 != ?s2).

# 2) STOP CODES

# 3) STOP NAMES
## a) A Stop must have a stop_name if the Stop is a StopLocation.
## b) A Stop must have a stop_name if the Stop is a Station.
## c) A Stop must have a stop_name if the Stop is an EntranceOrExit.

## 3a
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:StopLocation] ,
    NOT EXISTS ?name IN (
        [?s, gtfs:stop_name, ?name]
    ) .

## 3b
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Station] ,
    NOT EXISTS ?name IN (
        [?s, gtfs:stop_name, ?name]
    ) .

## 3c
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:EntranceOrExit] ,
    NOT EXISTS ?name IN (
        [?s, gtfs:stop_name, ?name]
    ) .

# 4) TTS STOP NAME

# 5) STOP DESCRIPTION

# 6) STOP LATITUDE
## a) A Stop must have a stop_lat if the Stop is a StopLocation.
## b) A Stop must have a stop_lat if the Stop is a Station.
## c) A Stop must have a stop_lat if the Stop is an EntranceOrExit.

## 6a
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:StopLocation] ,
    NOT EXISTS ?lat IN (
        [?s, gtfs:stop_lat, ?lat]
    ) .

## 6b
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Station] ,
    NOT EXISTS ?lat IN (
        [?s, gtfs:stop_lat, ?lat]
    ) .

## 6c
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:EntranceOrExit] ,
    NOT EXISTS ?lat IN (
        [?s, gtfs:stop_lat, ?lat]
    ) .

# 7) STOP LONGITUDE
## a) A Stop must have a stop_lon if the Stop is a StopLocation.
## b) A Stop must have a stop_lon if the Stop is a Station.
## c) A Stop must have a stop_lon if the Stop is an EntranceOrExit.

## 7a
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:StopLocation] ,
    NOT EXISTS ?lon IN (
        [?s, gtfs:stop_lon, ?lon]
    ) .

## 7b
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Station] ,
    NOT EXISTS ?lon IN (
        [?s, gtfs:stop_lon, ?lon]
    ) .

## 7c
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:EntranceOrExit] ,
    NOT EXISTS ?lon IN (
        [?s, gtfs:stop_lon, ?lon]
    ) .

# 8) ZONE IDS


# 9) LOCATION TYPES
## a) A Stop is a StopLocation if location_type is 0 or empty, and has no parent station.
## b) A Stop is a Platform if location_type is 0 or empty, and has a parent station.
## c) A Stop is a Station if location_type is 1.
## d) A Stop is an EntranceOrExit if location_type is 2.
## e) A Stop is a GenericNode if location_type is 3.
## f) A Stop is a BoardingArea if location_type is 4.

## 9a
[?s, rdf:type, gtfs:StopLocation] :-
    [?s, rdf:type, gtfs:Stop] ,
    [?s, gtfs:location_type, 0] ,
    NOT EXISTS ?x IN (
        [?s, rdf:type, gtfs:ChildStop]
    ) .

# 9b
[?s, rdf:type, gtfs:Platform] :-
    [?s, gtfs:location_type, 0],
    [?s, rdf:type, gtfs:ChildStop] .

# 9c
[?s, rdf:type, gtfs:Station] :-
    [?s, gtfs:location_type, 1] .

# 9d
[?s, rdf:type, gtfs:EntranceOrExit] :-
    [?s, gtfs:location_type, 2] .

# 9e
[?s, rdf:type, gtfs:GenericNode] :-
    [?s, gtfs:location_type, 3] .

# 9f
[?s, rdf:type, gtfs:BoardingArea] :-
    [?s, gtfs:location_type, 4] .


# 10) PARENT STATION
## a) A Stop is a ChildStop if it has a parent station.
## b) A Stop is a ParentlessStop if it has no parent station.
## c) An EntranceOrExit must have a parent station.
## d) A GenericNode must have a parent station.
## e) A BoardingArea must have a parent station.
## f) A Station must not have a parent station.

# 10a
[?s, rdf:type, gtfs:ChildStop] :-
    [?s, gtfs:parent_station, ?ps] .

# 10b
[?s, rdf:type, gtfs:ParentlessStop] :-
    [?s, rdf:type, gtfs:Stop] ,
    NOT EXISTS ?ps IN (
        [?s, rdf:type, gtfs:ChildStop]
    ) .

# 10c
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:EntranceOrExit] ,
    NOT EXISTS ?i IN (
        [?s, gtfs:parent_station, ?i]
    ) .

# 10d
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:GenericNode] ,
    NOT EXISTS ?i IN (
        [?s, gtfs:parent_station, ?i]
    ) .

# 10e
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:BoardingArea] ,
    NOT EXISTS ?i IN (
        [?s, gtfs:parent_station, ?i]
    ) .

# 10f
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Station] ,
    [?s, gtfs:parent_station, ?ps] .


# 11) STOP TIMEZONE

# 12) WHEELCHAIR BOARDING

# 13) LEVEL ID

# 14) PLATFORM CODE

# 15) STOP_ACCESS
# 15a) A Station must not have a stop_access.
# 15b) An EntranceOrExit must not have a stop_access.
# 15c) A GenericNode must not have a stop_access.
# 15d) A BoardingArea must not have a stop_access.
# 15e) A ParentlessStop must not have a stop_access.

# 15a
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:Station] ,
    [?s, gtfs:stop_access, ?i] .

# 15b
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:EntranceOrExit] ,
    [?s, gtfs:stop_access, ?i] .

# 15c
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:GenericNode] ,
    [?s, gtfs:stop_access, ?i] .

# 15d
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:BoardingArea] ,
    [?s, gtfs:stop_access, ?i] .

# 15e
[?s, rdf:type, gtfs:Violation] :-
    [?s, rdf:type, gtfs:ParentlessStop] ,
    [?s, gtfs:stop_access, ?i] .